### ISSUE TITLE
Mejora el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-MartaSobrino#1]
Buen trabajo @MartaSobrino !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes, ten cuidado de no escribir demasiadas {} y acabar pasando un objeto
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props, siempre que pases props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by oneeyedman** [comment]
Hola, @MartaSobrino: está todo genial excepto el sistema de los favoritos. Si quieres mañana nos sentamos y lo vemos.

**Comment by MartaSobrino** [comment]
Por favor 🙂

**Comment by oneeyedman** [comment]
Buén trabajo, @MartaSobrino, lo damos por resuelto!
